ADD: Registration controller
E-cell-NITS/Srijan-2023-api pull request #2
Opened 2023-02-26 14:07 UTC by JDeepD

2023-02-27 06:55 UTC, JOSU9435 reviewed
- rename the file src/controllers/registration/registration.ts to "add.ts" or "create.ts"

Since it is in the directory named registration it is understood that the controllers in this dir. are performing operations on the registration model and their file name should specify the kind of operation it's performing

- change src/middlewares/validations.ts to src/middlewares/registration/validation.ts

So that we could infer that the validtions.ts middleware is to be used for the registration routes

2023-02-27 06:57 UTC, JOSU9435 requested changes
- rename the file src/controllers/registration/registration.ts to "add.ts" or "create.ts"

Since it is in the directory named registration it is understood that the controllers in this dir. are performing operations on the registration model and their file name should specify the kind of operation it's performing

- change src/middlewares/validations.ts to src/middlewares/registration/validation.ts

So that we could infer that the validtions.ts middleware is to be used for the registration routes

2023-02-27 07:12 UTC, JDeepD commented
> * rename the file src/controllers/registration/registration.ts to "add.ts" or "create.ts"
> 
> Since it is in the directory named registration it is understood that the controllers in this dir. are performing operations on the registration model and their file name should specify the kind of operation it's performing

Will do.

> * change src/middlewares/validations.ts to src/middlewares/registration/validation.ts
> 
> So that we could infer that the validtions.ts middleware is to be used for the registration routes

Can do this but `validation.ts` can actually log **any errors** (Not  just in registration). (It just logs errors that happened in previous middleware VALIDATORS). So its not  used **only** for registration validation.

2023-02-27 08:18 UTC, JOSU9435 commented
ok then no issues regarding validation.ts

2023-02-27 17:43 UTC, JOSU9435 requested changes

2023-02-27 17:43 UTC, JOSU9435 commented on src/middlewares/registration/checkIsTeamEvent.ts
> +export default checkIsTeamEvent;
if we are checking for min and max team members is there no reason to check for isTeamEvent

2023-02-27 17:43 UTC, JOSU9435 commented on src/controllers/registration/create.ts
> +  }
I think this check here is not required if you are checking for min and max members in middleware

2023-02-28 07:28 UTC, JOSU9435 approved these changes

2023-02-28 07:28 UTC, merged